export const portfolioSection = {
  id: "portfolio",
  primary: false,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  logoName: "Github",
  topLine: "Created with React",
  headline: "My Portfolio Website",
  description: "A showcase of my projects",
  buttonLabel: "Source Code",
  btnLink1: "https://github.com/hashimkhanzada/react-portfolio-website",
  imgStart: "",
  img: require("../../images/react-logo.svg").default,
  alt: "React Logo",
  start: "",
};

export const aboutMeSection = {
  id: "aboutMe",
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  skills: true,
  techsUsed: false,
  logoName: "Resume",
  AboutMeHeader: "ABOUT ME",
  headline: "Full-stack .NET developer",
  description:
    "A software engineering graduate of UCOL, with a passion for developing exciting software.",
  description2:
    "A fast learner with strong time management and problem solving skills. I've successfully worked on multiple team projects during my degree, where communication skills and teamwork is essential. ",
  buttonLabel: "View Resume",
  btnLink1: require("../../images/hashim-cv.pdf").default,
  imgStart: "start",

  img1: require("../../images/dotnet.svg").default,
  tip1: ".Net Core",
  img2: require("../../images/csharp.svg").default,
  tip2: "C Sharp",
  img3: require("../../images/sql.svg").default,
  tip3: "SQL Server",
  img4: require("../../images/jquery.svg").default,
  tip4: " jQuery ",
  img5: require("../../images/react.svg").default,
  tip5: " React Js",
  img6: require("../../images/html.svg").default,
  tip6: " HTML ",
  img7: require("../../images/css.svg").default,
  tip7: " CSS ",
  img8: require("../../images/javascript.svg").default,
  tip8: " JavaScript ",
  img9: require("../../images/azure.svg").default,
  tip9: " Azure ",
  img10: require("../../images/firebase.svg").default,
  tip10: " Firebase ",
  img11: require("../../images/vue.svg").default,
  tip11: " Vue Js ",
  img12: require("../../images/vuetify.svg").default,
  tip12: " Vuetify ",
  img13: require("../../images/kotlin.svg").default,
  tip13: " Kotlin ",
  img14: require("../../images/materialui.svg").default,
  tip14: "Material UI  ",
  img15: require("../../images/xamarin.svg").default,
  tip15: " Xamarin ",
  img16: require("../../images/caliburnmicro.svg").default,
  tip16: " Caliburn Micro ",
  img17: require("../../images/java.svg").default,
  tip17: " Java ",
  img18: require("../../images/dapper.svg").default,
  tip18: " Dapper ",
  img19: require("../../images/efcore.svg").default,
  tip19: " Entity Framework Core ",
  img20: require("../../images/materialdesignxaml.svg").default,
  tip20: " Material Design XAML ",
  alt: "Skills",
  start: "true",
};

export const dietTrackerSection = {
  id: "dietTracker",
  primary: false,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  techsUsed: true,
  logoName: "Github",
  logoName2: "Youtube",
  extraBtn: true,
  topLine: "Industry Project - sponsored by UCOL",
  headline: "Diet Tracking Software",
  description:
    "A diet tracking web application that utilizes the NzFoodFiles database and FatSecret API. " +
    "Users can search these extensive databases for food items, to track their nutrition. ",
  description2:
    "Users can use the in-built nutrient calculator to set goals, view a daily/weekly summary of their intakes, and export summaries in a csv format.",
  description3: "Technologies used:",
  buttonLabel: "Source Code",
  buttonLabel2: "Demo",
  btnLink1: "https://github.com/hashimkhanzada/Nutritional_Software",
  btnLink2: "https://youtu.be/h5HO1Ii3xj8",
  imgStart: "",
  img: require("../../images/food.svg").default,
  img1: require("../../images/dotnet.svg").default,
  tip1: ".Net Core",
  img2: require("../../images/csharp.svg").default,
  tip2: "C Sharp",
  img3: require("../../images/sql.svg").default,
  tip3: "SQL Server",
  img4: require("../../images/jquery.svg").default,
  tip4: "jQuery",
  img5: require("../../images/javascript.svg").default,
  tip5: "JavaScript",
  img6: require("../../images/html.svg").default,
  tip6: "HTML",
  img7: require("../../images/css.svg").default,
  tip7: "CSS",
  img8: require("../../images/azure.svg").default,
  tip8: "Azure",

  alt: "Vault",
  start: "",
};

export const planStudyOptionsSection = {
  id: "planStudyOptions",
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  techsUsed: true,
  logoName: "Github",
  topLine: "WPF | Caliburn Micro",
  headline: "Plan Study Options",
  description:
    "A desktop application to aid UCOL BICT (Bachelor's in ICT) students in planning their study options. Gives students the available list of courses, calculates their credits, and shows them the courses they're eligible for based on the major they choose.",
  description2:
    "Uses Caliburn Micro as its MVVM framework, and Simple Container as its dependency injection system. Dapper is used as the ORM. Material Design XAML is used to style the UI components.",
  description3: "Technologies used:",
  buttonLabel: "Source Code",
  btnLink1: "https://github.com/hashimkhanzada/WPF.PlanStudyOptions",
  imgStart: "start",
  img: require("../../images/books.svg").default,
  img1: require("../../images/dotnet.svg").default,
  tip1: ".Net Core  ",
  img2: require("../../images/csharp.svg").default,
  tip2: "C Sharp ",
  img3: require("../../images/sql.svg").default,
  tip3: "SQL Server",
  img4: require("../../images/caliburnmicro.svg").default,
  tip4: "Caliburn Micro",
  img5: require("../../images/dapper.svg").default,
  tip5: "Dapper ",
  img6: require("../../images/materialdesignxaml.svg").default,
  tip6: "Material Design XAML",
  alt: "Skills",
  start: "true",
};

export const vueApp = {
  id: "vueApp",
  primary: false,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  techsUsed: true,
  logoName: "Azure",
  logoName2: "Youtube",
  extraBtn: true,
  topLine: "VueJs | Vuetify",
  headline: "Single Page Application",
  description:
    "A responsive SPA created with Vue, styled with Vuetify.  " +
    "It uses firebase google authentication to allow users to sign in with their google account.",
  description2:
    "It has an inventory that contains Vue components, allowing the users to perform CRUD operations, using the browsers local storage. ",
  description3: "Technologies used:",
  buttonLabel: "Source Code",
  buttonLabel2: "Demo",
  btnLink1: "https://dev.azure.com/hashimkhanzada/VueJs",
  btnLink2: "https://youtu.be/lmg2hHx8lVA",
  imgStart: "",
  img: require("../../images/onboard.svg").default,
  img1: require("../../images/vue.svg").default,
  tip1: "Vue Js",
  img2: require("../../images/vuetify.svg").default,
  tip2: "Vuetify ",
  img3: require("../../images/firebase.svg").default,
  tip3: "Firebase ",

  alt: "Skills",
  start: "",
};

export const tuckbox = {
  id: "tuckbox",
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  techsUsed: true,
  download: true,
  logoName: "Zip",
  logoName2: "Youtube",
  extraBtn: true,
  topLine: "JAVA | KOTLIN",
  headline: "TUCKBOX",
  description:
    "An android application for placing/managing lunch delivery orders. Uses firebase firestore as its remote database, and ROOM as its ORM.",
  description2:
    "Allows users to register/login, place/manage delivery orders, and manage their profiles.",
  description3: "Technologies used:",
  buttonLabel: "Download ZIP",
  buttonLabel2: "Demo",
  btnLink1: require("../../images/TuckBox.zip").default,
  btnLink2: "https://youtu.be/8MQ8BU053t8",
  imgStart: "start",
  img: require("../../images/phonelogo.svg").default,
  img1: require("../../images/java.svg").default,
  tip1: "Java",
  img2: require("../../images/kotlin.svg").default,
  tip2: "Kotlin",
  img3: require("../../images/firebase.svg").default,
  tip3: "Firebase",
  img4: require("../../images/android.svg").default,
  tip4: "Android",
  img5: require("../../images/materialui.svg").default,
  tip5: "Material UI ",
  alt: "Skills",
  start: "true",
};

export const intercity = {
  id: "intercity",
  primary: false,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  techsUsed: true,
  logoName: "Github",
  // logoName2: "Youtube",
  // extraBtn: true,
  topLine: "ASP.NET | Xamarin | React",
  headline: "InterCity Clone",
  description:
    "An InterCity clone application with multiple user interfaces and a shared library. Currently has a web and mobile UI, for different purposes. " +
    ".",
  description2:
    "Web interface for customers to register/login, and create/manage bookings. Mobile interface for bus drivers to check-in customers.",
  description3: "Technologies used:",
  buttonLabel: "In Progress",
  btnLink1: "#",
  // btnLink2: "/",
  // buttonLabel2: "Demo",
  imgStart: "",
  img: require("../../images/travel.svg").default,
  img1: require("../../images/dotnet.svg").default,
  tip1: ".Net Core  ",
  img2: require("../../images/csharp.svg").default,
  tip2: "C Sharp",
  img3: require("../../images/react.svg").default,
  tip3: "React",
  img4: require("../../images/xamarin.svg").default,
  tip4: "Xamarin ",
  img5: require("../../images/sql.svg").default,
  tip5: "SQL Server ",
  img6: require("../../images/javascript.svg").default,
  tip6: "JavaScript",
  img7: require("../../images/dapper.svg").default,
  tip7: "Dapper ",

  alt: "Skills",
  start: "",
};
