name: Deploy to gh pages

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "hashimkhanzada" && git config user.email "hashimkhanzada@gmail.com"
          CI= npm run deploy
